import Footer from '@/components/Footer'
import Header from '@/components/Header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="flex items-center h-[100vh] bg-transparent text-white">
          <div className="lg:ml-96 md:ml-52 ml-16 bg-[#AB4F81]/40 backdrop-blur-sm text-center rounded-xl w-96 min-h-96 py-5">
            <h1 className="font-semibold">
              "MOTION DESIGN KEEP PEOPLE WONDERING"
            </h1>
            <h1 className="text-6xl pt-10 font-bold">MDK.PW</h1>
            <p className="mt-4 text-base">
              Абсолютно любая работа для вашего проекта, которая подается с
              душой и уникальными ходовыми функциями.
            </p>
            <button className="mt-6 px-6 py-3 bg-pink-600 text-white font-semibold">
              Заказать
            </button>
          </div>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
